### ISSUE TITLE
HELP NEEDED: Container has not sufficient rights

### ISSUE THREAD

**Issue by ojsef39** [onedr0p/intel-gpu-exporter#22]
Hey, found this project and it's precisely what i searched for. Unfortunetely iam not able to get the docker container running via docker compose.

The Error:
`Error: Failed to initialize PMU! (Operation not permitted)`

My compose file:
```
version: "3.3"

services:
  intel_gpu-exporter:
    image: ghcr.io/onedr0p/intel-gpu-exporter:rolling
    container_name: intel_gpu-exporter
    environment:
      - GID=226
    ports:
      - 8081:8080
    #restart: unless-stopped
    #command: "ls / && echo && ls -la /dev/dri/"
    #entrypoint: ""
    volumes:
      - /dev/dri/card0:/dev/dri/card0
```

I tried multiple solutions:
- binding in also render128
- user: 0:0
- GID to same group as video (card0 group)

FYI: It works on the host

Im lost and for any help im really grateful, thanks in advance, maybe i just missed something.

**Comment by onedr0p** [comment]
Did you try `privileged: true` ?

**Comment by ojsef39** [comment]
Hey @onedr0p found that out now too :) BUT big thanks for your fast reply. Would it be possible to add like an example to your readme for future idiots like me lol?

here is how i have it now for others who see this:

```
version: "3.3"

services:
  intel_gpu-exporter:
    image: ghcr.io/onedr0p/intel-gpu-exporter:rolling
    container_name: intel_gpu-exporter
    privileged: true
    pid: host
    ports:
      - 8081:8080
    restart: unless-stopped
    volumes:
      - /dev/dri/:/dev/dri/
```
