### ISSUE TITLE
After last docker image update stop working

### ISSUE THREAD

**Issue by webysther** [onedr0p/intel-gpu-exporter#25]
![image](https://github.com/onedr0p/intel-gpu-exporter/assets/750007/fbac8874-03fe-4ca1-9efc-1f16a43c62af)

No information is showing in the stats page and no error in log output:

<img width="373" alt="image" src="https://github.com/onedr0p/intel-gpu-exporter/assets/750007/f0fc5829-42fe-4162-91b2-f9bd8fb48fed">

I'm using this:

```yml
  intel-gpu:
    image: ghcr.io/onedr0p/intel-gpu-exporter:rolling
    container_name: app-intel-gpu-exporter
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    expose:
      - 8080
    networks:
      prometheus:
    restart: unless-stopped
```

Change devices to volumes make no diff.
I have no pid either before the update and works just fine, I put pid also but don't work either.
